---
title: "Web Scraping Example"
author: "Lamar Foster"
date: "2/20/2021"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
library(gganimate)
library(ggthemes)
library(lubridate)
library(ggrepel)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Scrape Movie Data 
link <- "https://www.imdb.com/chart/top/"
page <- read_html(link)
name <-  page %>% html_nodes(".titleColumn a") %>% html_text()
year <- page %>% html_nodes(".secondaryInfo") %>% html_text()
rating <- page %>% html_nodes("strong") %>% html_text()

#Turn into data frame 
movies <- data.frame(name, year, rating, stringsAsFactors = F)

movies <- movies %>% 
mutate(ranking = seq(1,250))
```

```{r}
#Data cleaning 
movies <- movies %>% 
  mutate(year = parse_number(year)) %>% 
  mutate(rating = as.numeric(rating))

```


```{r}
movies %>% 
group_by(year) %>% 
filter(year > "2000") %>% 
summarise(rating = mean(rating)) %>% 
arrange(rating) %>% 
ggplot(aes(year, rating)) + 
scale_y_continuous(breaks = seq(2000,2020, by = 5)) +
geom_col()
```

```{r}
#Visualize Movies Data Set 
movies %>% 
group_by(year, ranking) %>% 
summarise(rating = mean(rating)) %>% 
ggplot(aes(x = ranking, y=rating, size = year)) +
  geom_point(show.legend = FALSE, alpha = 0.7) +
  labs(x = "Ranking", y = "Average Rating") + 
  theme_tufte() +
  transition_time(year) +
  labs(title = "Year: {frame_time}")
```

```{r}
link_school <- "https://www.greatschools.org/search/search.zipcode?sort=rating&zip=37043"
page_school <- read_html(link)
name_school <-  page %>% html_nodes(".name") %>% html_attr()
rating_school <- page %>% html_nodes("strong") %>% html_text()
```



```{r}
#Scrape WA Min Wage Data 
link <- "https://lni.wa.gov/workers-rights/wages/minimum-wage/history-of-washington-states-minimum-wage"
page <- read_html(link)
year <- page %>% html_nodes("td:nth-child(1)") %>% html_text()
wage <- page %>% html_nodes("td+ td") %>% html_text()

#Turn into data frame 
minwa <- data.frame(year, wage, stringsAsFactors = F)
```

```{r}
# Clean Min Wage Data frame 
minwa_clean <- minwa %>% 
  slice(-1) %>% 
  mutate(wage = parse_number(wage),
         year = mdy(year),
         year = year(year))
```

```{r}
#Visualize the data
minwa_clean %>% 
ggplot(aes(x = year, y = wage)) +
  geom_point(color = "#85754d", aes(group = year)) +
  geom_line(color = "#4b2e83") + 
  scale_x_continuous(breaks = seq(from = 1960, to = 2020, by = 10)) +
  scale_y_continuous(breaks= seq(from = 0, to = 15, by = 3),
                     labels = scales::dollar) +
  labs(title = "Washington State Minimum Wage Change",
       subtitle = "From 1960 to 2021",
       x = "Year",
       y = "Minimum Wage") +
  geom_label(data = minwa_clean %>% filter(wage > 13.6), aes(label = scales::dollar(wage))) +
  theme_classic() + 
  transition_reveal(year)
  
```




